# Generated by Django 3.2.4 on 2021-07-04 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Patronymic')),
                ('age_driver', models.SmallIntegerField(verbose_name='age')),
                ('experience', models.CharField(choices=[('1', 'up to 1 year'), ('3', 'from 1 to 3 years'), ('5', 'from 3 to 5 years')], max_length=1, null=True)),
                ('languages', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic'), ('kg', 'Kyrgyz')], max_length=2, null=True)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
