# Generated by Django 3.2.4 on 2021-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='languages2',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic'), ('kg', 'Kyrgyz')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='languages3',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic'), ('kg', 'Kyrgyz')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='languages',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic'), ('kg', 'Kyrgyz')], max_length=2, null=True),
        ),
    ]
