# Generated by Django 3.2.4 on 2021-07-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Dwelling name')),
                ('count_room', models.IntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prise')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Rating')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImageGalery', to='home.imagegalery', verbose_name='image')),
            ],
        ),
    ]
