# Generated by Django 3.2.4 on 2021-07-03 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210703_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='conditioner',
            field=models.BooleanField(default=True, verbose_name='The presence of an air conditioner'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='count_room',
            field=models.SmallIntegerField(default=1, verbose_name='Number of rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodging',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Title'),
        ),
    ]
