# Generated by Django 3.2.4 on 2021-07-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210703_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingimage',
            name='lodging',
        ),
        migrations.AddField(
            model_name='lodgingimage',
            name='lodging_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.lodging'),
        ),
    ]
