# Generated by Django 3.2.4 on 2021-07-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210703_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingimage',
            old_name='lodging_id',
            new_name='lodging',
        ),
    ]
