# Generated by Django 3.2.4 on 2021-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_lodging_id_lodgingimage_lodging'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='category',
            field=models.CharField(choices=[('H', 'Hotel'), ('Y', 'Yurts'), ('A', 'Apartments'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
