 # Generated by Django 3.2.4 on 2021-07-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_alter_lodging_category'),
        ('car', '0002_alter_carsmodel_car_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=50, verbose_name='Name tour')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(blank=True, choices=[('', ''), ('', ''), ('', '')], max_length=2, null=True)),
                ('numbers_of_day', models.CharField(blank=True, choices=[('4', '1-4'), ('8', '1-8'), ('10', '1-10'), ('14', '1-14')], max_length=2, null=True)),
                ('cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carsmodel', verbose_name='Car')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lodging', verbose_name='Home')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plane.plannedtour')),
            ],
        ),
    ]
